version: '2'

services:
  proxy:
    image: nginx
    volumes:
      - $PWD/public:/usr/share/nginx/html:ro
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app

  app:
    image: node
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: bash -c "npm rebuild && npm run dev"
    networks:
      - app
    depends_on:
      - db 

  db:
    image: postgres
    networks:
      - app
    ports:
      - "5000:5432"
    volumes:
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./scripts/sql:/scripts

networks:
  app:
